### ISSUE TITLE
过渡视频

### ISSUE THREAD

**Issue by Tong-Hao741** [Vchitect/SEINE#17]
hi作者你好，我已经成功运行with_mask_sample.py文件完成了生成预测视频任务，那么下一步我应该如何测试过渡任务呢？例如运行那个文件等？

**Comment by maxin-cn** [comment]
> hi作者你好，我已经成功运行with_mask_sample.py文件完成了生成预测视频任务，那么下一步我应该如何测试过渡任务呢？例如运行那个文件等？

Run `python sample_scripts/with_mask_sample.py --config configs/sample_transition.yaml`.

**Comment by Tong-Hao741** [comment]
thank u ^_^
