### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by waternight1029** [Vchitect/SEINE#6]
When I try 
`python sample_scripts/with_mask_sample.py --config configs/sample_i2v.yaml`

Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\diffusers\configuration_utils.py", line 106, in register_to_config
    setattr(self, key, value)
  File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1723, in __setattr__
    raise AttributeError(
AttributeError: cannot assign module before Module.__init__() call

Another one:
AttributeError: 'Transformer3DModel' object has no attribute '_modules'

**Comment by maxin-cn** [comment]
> When I try `python sample_scripts/with_mask_sample.py --config configs/sample_i2v.yaml`
> 
> Traceback (most recent call last): File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\diffusers\configuration_utils.py", line 106, in register_to_config setattr(self, key, value) File "C:\Users\xxxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\module.py", line 1723, in **setattr** raise AttributeError( AttributeError: cannot assign module before Module.**init**() call
> 
> Another one: AttributeError: 'Transformer3DModel' object has no attribute '_modules'

@waternight1029 Hi, the `diffusers` version you installed may not be the same as the `diffusers` version we tested. Please check your `diffusers` version.

**Comment by waternight1029** [comment]
It works! Thank you so much!
